server:
  port: 8501

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.150.131
      port: 6379
      password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location:  classpath:/mybatis-config.xml
